package avutil

//#include <libavutil/channel_layout.h>
//#include <stdlib.h>
import "C"

const (
	AV_CH_FRONT_LEFT            = int64(C.AV_CH_FRONT_LEFT)
	AV_CH_FRONT_RIGHT           = int64(C.AV_CH_FRONT_RIGHT)
	AV_CH_FRONT_CENTER          = int64(C.AV_CH_FRONT_CENTER)
	AV_CH_BACK_LEFT             = int64(C.AV_CH_BACK_LEFT)
	AV_CH_BACK_RIGHT            = int64(C.AV_CH_BACK_RIGHT)
	AV_CH_FRONT_LEFT_OF_CENTER  = int64(C.AV_CH_FRONT_LEFT_OF_CENTER)
	AV_CH_FRONT_RIGHT_OF_CENTER = int64(C.AV_CH_FRONT_RIGHT_OF_CENTER)

	AV_CH_LAYOUT_MONO           = int64(C.AV_CH_LAYOUT_MONO)
	AV_CH_LAYOUT_STEREO         = int64(C.AV_CH_LAYOUT_STEREO)
	AV_CH_LAYOUT_2_1            = int64(C.AV_CH_LAYOUT_2_1)
	AV_CH_LAYOUT_SURROUND       = int64(C.AV_CH_LAYOUT_SURROUND)
	AV_CH_LAYOUT_4POINT0        = int64(C.AV_CH_LAYOUT_4POINT0)
	AV_CH_LAYOUT_2_2            = int64(C.AV_CH_LAYOUT_2_2)
	AV_CH_LAYOUT_QUAD           = int64(C.AV_CH_LAYOUT_QUAD)
	AV_CH_LAYOUT_5POINT0        = int64(C.AV_CH_LAYOUT_5POINT0)
	AV_CH_LAYOUT_5POINT1        = int64(C.AV_CH_LAYOUT_5POINT1)
	AV_CH_LAYOUT_5POINT0_BACK   = int64(C.AV_CH_LAYOUT_5POINT0_BACK)
	AV_CH_LAYOUT_5POINT1_BACK   = int64(C.AV_CH_LAYOUT_5POINT1_BACK)
	AV_CH_LAYOUT_7POINT0        = int64(C.AV_CH_LAYOUT_7POINT0)
	AV_CH_LAYOUT_7POINT1        = int64(C.AV_CH_LAYOUT_7POINT1)
	AV_CH_LAYOUT_7POINT1_WIDE   = int64(C.AV_CH_LAYOUT_7POINT1_WIDE)
	AV_CH_LAYOUT_STEREO_DOWNMIX = int64(C.AV_CH_LAYOUT_STEREO_DOWNMIX)
)

func AvGetDefaultChannelLayout(numChannels int) int64 {
	num := C.int(numChannels)
	ret := C.av_get_default_channel_layout(num)
	return int64(ret)
}
